import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import ThemeSwitcher from "./components/ThemeSwitcher";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-lightbg text-black dark:bg-darkbg dark:text-white`}
      >
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
        <footer className="row-start-3 flex gap-4 sm:gap-6 flex-wrap items-center justify-center">
          <p className="text-sm sm:text-base">Template</p>
        </footer>
      </body>
    </html>
  );
}
