import type { Metadata } from "next";
import { Montserrat, Noto_Sans } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"]
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

// TODO - Fix metadata

export const metadata: Metadata = {
  title: "Vedemöstäd",
  description: "Generated by create next app",
};

/**
 * Returns teh root layout of the application, visible on all the pages of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${notoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
